# Project: Проект1
# Makefile created by Dev-C++ 5.8.2

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o binary_tree.o
LINKOBJ  = main.o binary_tree.o
LIBS     = -L"D:/PROGRAMMING/Distributives/Dev-Cpp/Dev-Cpp/MinGW64/lib" -L"D:/PROGRAMMING/Distributives/Dev-Cpp/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"D:/PROGRAMMING/Distributives/Dev-Cpp/Dev-Cpp/MinGW64/include" -I"D:/PROGRAMMING/Distributives/Dev-Cpp/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/PROGRAMMING/Distributives/Dev-Cpp/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"
CXXINCS  = -I"D:/PROGRAMMING/Distributives/Dev-Cpp/Dev-Cpp/MinGW64/include" -I"D:/PROGRAMMING/Distributives/Dev-Cpp/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/PROGRAMMING/Distributives/Dev-Cpp/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"D:/PROGRAMMING/Distributives/Dev-Cpp/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++"
BIN      = 1.8_Binary_Tree.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

binary_tree.o: binary_tree.cpp
	$(CPP) -c binary_tree.cpp -o binary_tree.o $(CXXFLAGS)
