# Project: Проект3
# Makefile created by Dev-C++ 5.8.2

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Main.o Bin_Tree.o
LINKOBJ  = Main.o Bin_Tree.o
LIBS     = -L"D:/PROGRAMMING/Distributives/Dev-Cpp/Dev-Cpp/MinGW64/lib" -L"D:/PROGRAMMING/Distributives/Dev-Cpp/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -mwindows -g3
INCS     = -I"D:/PROGRAMMING/Distributives/Dev-Cpp/Dev-Cpp/MinGW64/include" -I"D:/PROGRAMMING/Distributives/Dev-Cpp/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/PROGRAMMING/Distributives/Dev-Cpp/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"
CXXINCS  = -I"D:/PROGRAMMING/Distributives/Dev-Cpp/Dev-Cpp/MinGW64/include" -I"D:/PROGRAMMING/Distributives/Dev-Cpp/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/PROGRAMMING/Distributives/Dev-Cpp/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"D:/PROGRAMMING/Distributives/Dev-Cpp/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++"
BIN      = Bin_Tree.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Main.o: Main.cpp
	$(CPP) -c Main.cpp -o Main.o $(CXXFLAGS)

Bin_Tree.o: Bin_Tree.cpp
	$(CPP) -c Bin_Tree.cpp -o Bin_Tree.o $(CXXFLAGS)
