# Project: LIST
# Makefile created by Dev-C++ 5.8.2

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = list.o list_tester.o sem_11_ex_1.o
LINKOBJ  = list.o list_tester.o sem_11_ex_1.o
LIBS     = -L"D:/PROGRAMMING/Distributives/Dev-Cpp/Dev-Cpp/MinGW64/lib" -L"D:/PROGRAMMING/Distributives/Dev-Cpp/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"D:/PROGRAMMING/Distributives/Dev-Cpp/Dev-Cpp/MinGW64/include" -I"D:/PROGRAMMING/Distributives/Dev-Cpp/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/PROGRAMMING/Distributives/Dev-Cpp/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"
CXXINCS  = -I"D:/PROGRAMMING/Distributives/Dev-Cpp/Dev-Cpp/MinGW64/include" -I"D:/PROGRAMMING/Distributives/Dev-Cpp/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/PROGRAMMING/Distributives/Dev-Cpp/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"D:/PROGRAMMING/Distributives/Dev-Cpp/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++"
BIN      = LIST.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

list.o: list.cpp
	$(CPP) -c list.cpp -o list.o $(CXXFLAGS)

list_tester.o: list_tester.cpp
	$(CPP) -c list_tester.cpp -o list_tester.o $(CXXFLAGS)

sem_11_ex_1.o: sem_11_ex_1.cpp
	$(CPP) -c sem_11_ex_1.cpp -o sem_11_ex_1.o $(CXXFLAGS)
